# Generated by Django 4.0.4 on 2022-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Text_Editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practise',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('query', models.CharField(max_length=5000)),
            ],
        ),
    ]
