# Generated by Django 4.0.4 on 2022-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Text_Editor', '0002_practise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Practise',
        ),
    ]
